name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run all unit tests
      run: npm test
      id: all-tests
    
    - name: Run tests with coverage
      run: npm run test:coverage
      id: coverage-tests
    
    - name: Run mock-specific tests
      run: npm run test:mock
      id: mock-tests
    
    - name: Run stub-specific tests
      run: npm run test:stub  
      id: stub-tests
    
    - name: Run basic functionality tests
      run: npm run test:basic
      id: basic-tests
    
    - name: Test Results Summary
      run: |
        echo "✅ All tests completed successfully!"
        echo "📊 Test Categories Executed:"
        echo "   - All Unit Tests"
        echo "   - Mock Tests" 
        echo "   - Stub Tests"
        echo "   - Basic Functionality Tests"
        echo "   - Coverage Report Generated"
